<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icons8-math-96.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icons8-math-96.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.4.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="EditStudent.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>